-- AlterTable
ALTER TABLE "InvestmentPlan" ADD COLUMN IF NOT EXISTS "cashReserve" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "InvestmentPlan" ADD COLUMN IF NOT EXISTS "cashBuffer" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "InvestmentPlan" ADD COLUMN IF NOT EXISTS "preservationBucket" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "InvestmentPlan" ADD COLUMN IF NOT EXISTS "longTermGrowthTarget" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "InvestmentPlan" ADD COLUMN IF NOT EXISTS "sipMonthlyBudget" DOUBLE PRECISION NOT NULL DEFAULT 0;
